var d;
function e(a,b,c){this.extend(e,google.maps.OverlayView);this.c=a;this.a=[];this.l=[];this.sizes=[53,56,66,78,90];this.s=[];this.K=!1;c=c||{};this.m=c.gridSize||60;this.u=c.minimumClusterSize||2;this.U=c.maxZoom||null;this.s=c.styles||[];this.ha=c.imagePath||this.aa;this.ga=c.imageExtension||this.$;this.Z=!0;void 0!=c.zoomOnClick&&(this.Z=c.zoomOnClick);this.D=!1;void 0!=c.averageCenter&&(this.D=c.averageCenter);k(this);this.setMap(a);this.V=this.c.getZoom();var f=this;google.maps.event.addListener(this.c,"zoom_changed",
function(){var a=f.c.getZoom();f.V!=a&&(f.V=a,f.v())});google.maps.event.addListener(this.c,"idle",function(){f.o()});b&&b.length&&this.M(b,!1)}d=e.prototype;d.aa="https://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m";d.$="png";d.extend=function(a,b){return function(a){for(var b in a.prototype)this.prototype[b]=a.prototype[b];return this}.apply(a,[b])};d.onAdd=function(){this.K||(this.K=!0,l(this))};d.draw=function(){};
function k(a){if(!a.s.length)for(var b=0,c;c=a.sizes[b];b++)a.s.push({url:a.ha+(b+1)+"."+a.ga,height:c,width:c})}d.ca=function(){for(var a=this.A(),b=new google.maps.LatLngBounds,c=0,f;f=a[c];c++)b.extend(f.getPosition());this.c.fitBounds(b)};d.J=function(){return this.s};d.A=function(){return this.a};d.fa=function(){return this.a.length};d.ma=function(a){this.U=a};d.T=function(){return this.U};
d.P=function(a,b){for(var c=0,f=a.length,g=f;0!==g;)g=parseInt(g/10,10),c++;c=Math.min(c,b);return{text:f,index:c}};d.ka=function(a){this.P=a};d.R=function(){return this.P};d.M=function(a,b){for(var c=0,f;f=a[c];c++)q(this,f);b||this.o()};function q(a,b){b.G=!1;b.draggable&&google.maps.event.addListener(b,"dragend",function(){b.G=!1;a.W()});a.a.push(b)}d.C=function(a,b){q(this,a);b||this.o()};
function r(a,b){var c=-1;if(a.a.indexOf)c=a.a.indexOf(b);else for(var f=0,g;g=a.a[f];f++)if(g==b){c=f;break}if(-1==c)return!1;b.setMap(null);a.a.splice(c,1);return!0}d.ia=function(a,b){var c=r(this,a);return!b&&c?(this.v(),this.o(),!0):!1};d.ja=function(a,b){for(var c=!1,f=0,g;g=a[f];f++)g=r(this,g),c=c||g;if(!b&&c)return this.v(),this.o(),!0};d.ea=function(){return this.l.length};d.getMap=function(){return this.c};d.setMap=function(a){this.c=a};d.S=function(){return this.m};
d.la=function(a){this.m=a};d.I=function(a){var b=this.getProjection(),c=new google.maps.LatLng(a.getNorthEast().lat(),a.getNorthEast().lng()),f=new google.maps.LatLng(a.getSouthWest().lat(),a.getSouthWest().lng()),c=b.fromLatLngToDivPixel(c);c.x+=this.m;c.y-=this.m;f=b.fromLatLngToDivPixel(f);f.x-=this.m;f.y+=this.m;c=b.fromDivPixelToLatLng(c);b=b.fromDivPixelToLatLng(f);a.extend(c);a.extend(b);return a};d.ba=function(){this.v(!0);this.a=[]};
d.v=function(a){for(var b=0,c;c=this.l[b];b++)c.remove();for(b=0;c=this.a[b];b++)c.G=!1,a&&c.setMap(null);this.l=[]};d.W=function(){var a=this.l.slice();this.l.length=0;this.v();this.o();window.setTimeout(function(){for(var b=0,c;c=a[b];b++)c.remove()},0)};d.o=function(){l(this)};
function l(a){if(a.K)for(var b=new google.maps.LatLngBounds(a.c.getBounds().getSouthWest(),a.c.getBounds().getNorthEast()),b=a.I(b),c=0,f;f=a.a[c];c++)if(!f.G&&b.contains(f.getPosition())){for(var g=a,v=4E4,n=null,w=0,m=void 0;m=g.l[w];w++){var h=m.getCenter();if(h){var p=f.getPosition();if(h&&p)var x=(p.lat()-h.lat())*Math.PI/180,y=(p.lng()-h.lng())*Math.PI/180,h=Math.sin(x/2)*Math.sin(x/2)+Math.cos(h.lat()*Math.PI/180)*Math.cos(p.lat()*Math.PI/180)*Math.sin(y/2)*Math.sin(y/2),h=12742*Math.atan2(Math.sqrt(h),
Math.sqrt(1-h));else h=0;h<v&&(v=h,n=m)}}n&&n.O.contains(f.getPosition())?n.C(f):(m=new t(g),m.C(f),g.l.push(m))}}function t(a){this.i=a;this.c=a.getMap();this.m=a.S();this.u=a.u;this.D=a.D;this.f=null;this.a=[];this.O=null;this.w=new u(this,a.J())}d=t.prototype;
d.C=function(a){var b;a:if(this.a.indexOf)b=-1!=this.a.indexOf(a);else{b=0;for(var c;c=this.a[b];b++)if(c==a){b=!0;break a}b=!1}if(b)return!1;this.f?this.D&&(c=this.a.length+1,b=(this.f.lat()*(c-1)+a.getPosition().lat())/c,c=(this.f.lng()*(c-1)+a.getPosition().lng())/c,this.f=new google.maps.LatLng(b,c),z(this)):(this.f=a.getPosition(),z(this));a.G=!0;this.a.push(a);b=this.a.length;b<this.u&&a.getMap()!=this.c&&a.setMap(this.c);if(b==this.u)for(c=0;c<b;c++)this.a[c].setMap(null);b>=this.u&&a.setMap(null);
a=this.c.getZoom();if((b=this.i.T())&&a>b)for(a=0;b=this.a[a];a++)b.setMap(this.c);else this.a.length<this.u?A(this.w):(b=this.i.R()(this.a,this.i.J().length),this.w.setCenter(this.f),a=this.w,a.L=b,a.b&&(a.b.innerHTML=b.text),b=Math.max(0,a.L.index-1),b=Math.min(a.s.length-1,b),b=a.s[b],a.na=b.url,a.h=b.height,a.B=b.width,a.X=b.textColor,a.g=b.anchor,a.Y=b.textSize,a.N=b.backgroundPosition,a.F=b.iconAnchor,this.w.show());return!0};
d.getBounds=function(){for(var a=new google.maps.LatLngBounds(this.f,this.f),b=this.A(),c=0,f;f=b[c];c++)a.extend(f.getPosition());return a};d.remove=function(){this.w.remove();this.a.length=0;delete this.a};d.da=function(){return this.a.length};d.A=function(){return this.a};d.getCenter=function(){return this.f};function z(a){var b=new google.maps.LatLngBounds(a.f,a.f);a.O=a.i.I(b)}d.getMap=function(){return this.c};
function u(a,b){a.i.extend(u,google.maps.OverlayView);this.s=b;this.j=a;this.f=null;this.c=a.getMap();this.L=this.b=null;this.H=!1;this.setMap(this.c)}d=u.prototype;
d.onAdd=function(){this.b=document.createElement("DIV");if(this.H){var a=B(this,this.f);this.b.style.cssText=C(this,a);this.b.innerHTML=this.L.text}this.getPanes().overlayMouseTarget.appendChild(this.b);var b=this;google.maps.event.addDomListener(this.b,"click",function(a){var f=b.j.i;google.maps.event.trigger(f,"clusterclick",b.j,a);f.Z&&b.c.fitBounds(b.j.getBounds())});google.maps.event.addDomListener(this.b,"mouseover",function(a){google.maps.event.trigger(b.j.i,"clustermouseover",b.j,a)});google.maps.event.addDomListener(this.b,
"mouseout",function(a){google.maps.event.trigger(b.j.i,"clustermouseout",b.j,a)})};function B(a,b){var c=a.getProjection().fromLatLngToDivPixel(b);"object"===typeof a.F&&2===a.F.length?(c.x-=a.F[0],c.y-=a.F[1]):(c.x-=parseInt(a.B/2,10),c.y-=parseInt(a.h/2,10));return c}d.draw=function(){if(this.H){var a=B(this,this.f);this.b.style.top=a.y+"px";this.b.style.left=a.x+"px"}};function A(a){a.b&&(a.b.style.display="none");a.H=!1}
d.show=function(){if(this.b){var a=B(this,this.f);this.b.style.cssText=C(this,a);this.b.style.display=""}this.H=!0};d.remove=function(){this.setMap(null)};d.onRemove=function(){this.b&&this.b.parentNode&&(A(this),this.b.parentNode.removeChild(this.b),this.b=null)};d.setCenter=function(a){this.f=a};
function C(a,b){var c=[];c.push("background-image:url("+a.na+");");c.push("background-position:"+(a.N?a.N:"0 0")+";");"object"===typeof a.g?("number"===typeof a.g[0]&&0<a.g[0]&&a.g[0]<a.h?c.push("height:"+(a.h-a.g[0])+"px; padding-top:"+a.g[0]+"px;"):"number"===typeof a.g[0]&&0>a.g[0]&&-a.g[0]<a.h?c.push("height:"+a.h+"px; line-height:"+(a.h+a.g[0])+"px;"):c.push("height:"+a.h+"px; line-height:"+a.h+"px;"),"number"===typeof a.g[1]&&0<a.g[1]&&a.g[1]<a.B?c.push("width:"+(a.B-a.g[1])+"px; padding-left:"+
a.g[1]+"px;"):c.push("width:"+a.B+"px; text-align:center;")):c.push("height:"+a.h+"px; line-height:"+a.h+"px; width:"+a.B+"px; text-align:center;");c.push("cursor:pointer; top:"+b.y+"px; left:"+b.x+"px; color:"+(a.X?a.X:"black")+"; position:absolute; font-size:"+(a.Y?a.Y:11)+"px; font-family:Arial,sans-serif; font-weight:bold");return c.join("")}window.MarkerClusterer=e;e.prototype.addMarker=e.prototype.C;e.prototype.addMarkers=e.prototype.M;e.prototype.clearMarkers=e.prototype.ba;
e.prototype.fitMapToMarkers=e.prototype.ca;e.prototype.getCalculator=e.prototype.R;e.prototype.getGridSize=e.prototype.S;e.prototype.getExtendedBounds=e.prototype.I;e.prototype.getMap=e.prototype.getMap;e.prototype.getMarkers=e.prototype.A;e.prototype.getMaxZoom=e.prototype.T;e.prototype.getStyles=e.prototype.J;e.prototype.getTotalClusters=e.prototype.ea;e.prototype.getTotalMarkers=e.prototype.fa;e.prototype.redraw=e.prototype.o;e.prototype.removeMarker=e.prototype.ia;e.prototype.removeMarkers=e.prototype.ja;
e.prototype.resetViewport=e.prototype.v;e.prototype.repaint=e.prototype.W;e.prototype.setCalculator=e.prototype.ka;e.prototype.setGridSize=e.prototype.la;e.prototype.setMaxZoom=e.prototype.ma;e.prototype.onAdd=e.prototype.onAdd;e.prototype.draw=e.prototype.draw;t.prototype.getCenter=t.prototype.getCenter;t.prototype.getSize=t.prototype.da;t.prototype.getMarkers=t.prototype.A;u.prototype.onAdd=u.prototype.onAdd;u.prototype.draw=u.prototype.draw;u.prototype.onRemove=u.prototype.onRemove;
